name: ğŸ§¾ QR Code Generator
run-name: "QR Code Generation"

on:
  push:
    branches: [ qr_code ]

jobs:
  generate_qr_code:
    runs-on: ubuntu-latest

    steps:
    - name: ğŸ“¦ Checkout Repository
      uses: actions/checkout@v4

    - name: ğŸ Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: ğŸ“¥ Install Dependencies
      run: pip install qrcode[pil]

    - name: ğŸ› ï¸ Run QR Code Generator
      run: python generate_qr.py

    - name: ğŸ“¤ Upload QR Code Image as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: contact_qr_codes
        path: contact_*.png
